FROM node:latest as build

WORKDIR /app

# 日本語フォントのインストール
RUN apt-get update && \
    apt-get install -y fonts-noto-cjk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# package.jsonとpackage-lock.jsonのコピー
COPY package*.json ./

# 依存関係のインストール
RUN npm install

# ポートの公開
EXPOSE 3000

# 開発サーバーの起動（ホットリロード有効）
CMD ["npm", "start"] 