version: '3.8'

services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:14-alpine
    container_name: event-matching-postgres
    restart: always
    environment:
      - POSTGRES_USER=eventuser
      - POSTGRES_PASSWORD=eventpass
      - POSTGRES_DB=eventdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventuser -d eventdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # バックエンドサービス
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: event-matching-backend
    restart: always
    environment:
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URI=postgresql://eventuser:eventpass@postgres:5432/eventdb
      - JWT_SECRET_KEY=your_jwt_secret_key_here
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
    volumes:
      - ./backend:/app
    ports:
      - "5000:5010"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/api/events"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "flask db upgrade && 
             flask run --host=0.0.0.0 --port=5010"

  # フロントエンドサービス
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: event-matching-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - TZ=Asia/Tokyo
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: npm start

# 永続化ボリューム
volumes:
  postgres-data:
    name: event-matching-postgres-data 